
DS_COMMON_PACKAGES = [
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "scipy",
    "sklearn",
    "transformer",
    "pytorch",
    "tensorflow",
    "keras",
    "torch",
    "nltk",
    "spacy",
    "gensim",
    "cv2",
    "dlib",
    "xgboost",
    "lightgbm",
    "catboost",
    "statsmodels",
    "plotly",
    "dash",
    "bokeh",
    "streamlit",
    "flask",
    "clicks",
    "django",
    "fastapi",
    "sqlalchemy",
    "pymongo",
    "pyodbc",
    "psycopg2",
    "pyarrow",
    "pandasql",
    "geopandas",
    "folium",
    "shapely",
    "networkx",
    "graphviz",
    "pydot",
    "pygraphviz",
    "dash",
]

def _load_common_ds_pkg():
    return DS_COMMON_PACKAGES